import { useEffect, useState, type FormEvent } from 'react'
import { AlertTriangle, CalendarDays, CheckCircle2, Edit3, PiggyBank, Plus, Trash2 } from 'lucide-react'
import { api, ApiError } from '../lib/api'
import { money, monthLabel } from '../lib/format'
import type { Budget, Category } from '../types'
import { EmptyState, FieldError, Modal, Spinner, useToast } from '../components/UI'

const alertText={normal:'En buen estado',warning:'Atención: superaste el 50%',critical:'Cuidado: superaste el 80%',limit_reached:'Límite alcanzado',exceeded:'Presupuesto excedido'}
export function BudgetsPage(){
  const now=new Date();const toast=useToast();const[period,setPeriod]=useState({year:now.getFullYear(),month:now.getMonth()+1});const[items,setItems]=useState<Budget[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[loading,setLoading]=useState(true)
  const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Budget|null>(null);const[form,setForm]=useState({categoryId:'',amount:''});const[errors,setErrors]=useState<Record<string,string[]>>({});const[busy,setBusy]=useState(false)
  const load=async()=>{setLoading(true);try{const[budgets,cats]=await Promise.all([api<Budget[]>(`/budgets?year=${period.year}&month=${period.month}`),api<Category[]>('/categories')]);setItems(budgets);setCategories(cats)}catch{toast.show('No se pudieron cargar los presupuestos.','error')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[period.year,period.month])
  const changeMonth=(offset:number)=>{const date=new Date(period.year,period.month-1+offset,1);setPeriod({year:date.getFullYear(),month:date.getMonth()+1})}
  const start=(item?:Budget)=>{setEditing(item??null);setErrors({});setForm(item?{categoryId:item.categoryId,amount:String(item.amount)}:{categoryId:'',amount:''});setOpen(true)}
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErrors({});try{const body={year:period.year,month:period.month,categoryId:form.categoryId,amount:Number(form.amount)};if(editing)await api(`/budgets/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/budgets',{method:'POST',body:JSON.stringify(body)});toast.show(`Presupuesto ${editing?'actualizado':'creado'}.`);setOpen(false);await load()}catch(error){if(error instanceof ApiError)setErrors(error.fields);toast.show(error instanceof Error?error.message:'No se pudo guardar.','error')}finally{setBusy(false)}}
  const remove=async(item:Budget)=>{if(!confirm(`¿Eliminar el presupuesto de ${item.categoryName}?`))return;try{await api(`/budgets/${item.id}`,{method:'DELETE'});toast.show('Presupuesto eliminado.');await load()}catch(error){toast.show(error instanceof Error?error.message:'No se pudo eliminar.','error')}}
  const total=items.reduce((sum,item)=>sum+item.amount,0),spent=items.reduce((sum,item)=>sum+item.spent,0),exceeded=items.filter(item=>item.isExceeded).length
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">PLANIFICACIÓN</span><h1>Presupuestos</h1><p>Define límites y recibe alertas antes de pasarte.</p></div><div className="heading-actions"><div className="period-switch"><button onClick={()=>changeMonth(-1)}>‹</button><span><CalendarDays size={17}/>{monthLabel(period.year,period.month)}</span><button onClick={()=>changeMonth(1)}>›</button></div><button className="btn primary" onClick={()=>start()}><Plus size={18}/>Nuevo presupuesto</button></div></div>
    <section className="mini-stats"><article><span><PiggyBank/></span><div><small>Planificado</small><strong>{money(total)}</strong></div></article><article><span className="amber"><CalendarDays/></span><div><small>Consumido</small><strong>{money(spent)}</strong></div></article><article><span className={exceeded?'red':'green'}>{exceeded?<AlertTriangle/>:<CheckCircle2/>}</span><div><small>Alertas críticas</small><strong>{exceeded}</strong></div></article></section>
    {loading?<Spinner/>:items.length?<div className="budget-grid">{items.map(item=><article className={`card budget-card ${item.alertLevel}`} key={item.id}><header><span className="catalog-icon" style={{background:`${item.categoryColor}18`,color:item.categoryColor}}><PiggyBank/></span><div><h3>{item.categoryName}</h3><p>{alertText[item.alertLevel]}</p></div><div className="card-actions"><button className="icon-btn" onClick={()=>start(item)}><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>remove(item)}><Trash2 size={17}/></button></div></header><div className="budget-numbers"><strong>{money(item.spent)}</strong><span>de {money(item.amount)}</span></div><div className="progress large"><i className={item.alertLevel} style={{width:`${Math.min(item.percentageUsed,100)}%`}}/></div><footer><span>{item.percentageUsed}% utilizado</span><span className={item.remaining<0?'text-danger':''}>{item.remaining>=0?`${money(item.remaining)} disponible`:`${money(Math.abs(item.remaining))} excedido`}</span></footer></article>)}</div>:<EmptyState icon={<PiggyBank/>} title="No hay presupuestos este mes" text="Crea límites por categoría para controlar mejor tus gastos."/>}
    <Modal open={open} title={editing?'Editar presupuesto':'Nuevo presupuesto'} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><div className="period-note"><CalendarDays/><span>Presupuesto para <strong>{monthLabel(period.year,period.month)}</strong></span></div><label><span>Categoría</span><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Selecciona...</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><FieldError errors={errors} name="categoryId"/></label><label><span>Límite mensual (RD$)</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00"/><FieldError errors={errors} name="amount"/></label><footer><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy}>{busy?'Guardando...':'Guardar presupuesto'}</button></footer></form></Modal>
  </div>
}
