import { useEffect, useState, type FormEvent } from 'react'
import { CircleDollarSign, CreditCard, Edit3, Plus, Search, Tags, Trash2, WalletCards } from 'lucide-react'
import { api, ApiError } from '../lib/api'
import type { Category, PaymentMethod } from '../types'
import { EmptyState, FieldError, Modal, Spinner, useToast } from '../components/UI'

type Kind = 'categories' | 'payment-methods'
const colors = ['#4F46E5','#2563EB','#0891B2','#059669','#65A30D','#D97706','#EA580C','#DC2626','#DB2777','#7C3AED']
const icons = ['wallet','credit-card','banknote','landmark','smartphone','circle-dollar-sign']

export function CatalogPage({ kind }: { kind: Kind }) {
  const isCategory = kind === 'categories'; const toast = useToast()
  const [items, setItems] = useState<(Category|PaymentMethod)[]>([]); const [loading,setLoading]=useState(true)
  const [search,setSearch]=useState(''); const [includeInactive,setIncludeInactive]=useState(false)
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Category|PaymentMethod|null>(null)
  const [form,setForm]=useState({name:'',detail:isCategory?'#4F46E5':'wallet',isActive:true})
  const [errors,setErrors]=useState<Record<string,string[]>>({}); const [busy,setBusy]=useState(false)
  const load=async()=>{setLoading(true);try{setItems(await api(`/${kind}?includeInactive=${includeInactive}`))}catch{toast.show('No se pudo cargar la lista.','error')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[kind,includeInactive])
  const start=(item?:Category|PaymentMethod)=>{setEditing(item??null);setErrors({});setForm(item?{name:item.name,detail:isCategory?(item as Category).color:(item as PaymentMethod).icon??'wallet',isActive:item.isActive}:{name:'',detail:isCategory?'#4F46E5':'wallet',isActive:true});setOpen(true)}
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErrors({});try{const body=isCategory?{name:form.name,color:form.detail,isActive:form.isActive}:{name:form.name,icon:form.detail,isActive:form.isActive};if(editing)await api(`/${kind}/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api(`/${kind}`,{method:'POST',body:JSON.stringify(body)});toast.show(`${isCategory?'Categoría':'Método de pago'} ${editing?'actualizado':'creado'}.`);setOpen(false);await load()}catch(error){if(error instanceof ApiError)setErrors(error.fields);toast.show(error instanceof Error?error.message:'No se pudo guardar.','error')}finally{setBusy(false)}}
  const remove=async(item:Category|PaymentMethod)=>{if(!confirm(`¿Eliminar "${item.name}"? Esta acción no se puede deshacer.`))return;try{await api(`/${kind}/${item.id}`,{method:'DELETE'});toast.show('Registro eliminado.');await load()}catch(error){toast.show(error instanceof Error?error.message:'No se pudo eliminar.','error')}}
  const filtered=items.filter(item=>item.name.toLowerCase().includes(search.toLowerCase()))
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">CONFIGURACIÓN</span><h1>{isCategory?'Categorías':'Métodos de pago'}</h1><p>{isCategory?'Organiza tus gastos con nombres y colores.':'Administra las formas en que realizas tus pagos.'}</p></div><button className="btn primary" onClick={()=>start()}><Plus size={18}/>Nuevo {isCategory?'categoría':'método'}</button></div>
    <div className="toolbar card"><div className="search-box"><Search/><input placeholder="Buscar por nombre..." value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="toggle"><input type="checkbox" checked={includeInactive} onChange={e=>setIncludeInactive(e.target.checked)}/><span/>Mostrar inactivos</label></div>
    {loading?<Spinner/>:filtered.length?<div className="catalog-grid">{filtered.map(item=><article className={`catalog-card card ${!item.isActive?'disabled':''}`} key={item.id}><span className="catalog-icon" style={isCategory?{background:`${(item as Category).color}18`,color:(item as Category).color}:{}}>{isCategory?<Tags/>:<CreditCard/>}</span><div><h3>{item.name}</h3><p>{item.isActive?'Disponible para nuevos gastos':'Inactivo'}</p>{isCategory?<span className="color-label"><i style={{background:(item as Category).color}}/>{(item as Category).color}</span>:<span className="color-label"><CircleDollarSign size={14}/>{(item as PaymentMethod).icon||'Sin icono'}</span>}</div><div className="card-actions"><button className="icon-btn" onClick={()=>start(item)} title="Editar"><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>remove(item)} title="Eliminar"><Trash2 size={17}/></button></div></article>)}</div>:<EmptyState icon={isCategory?<Tags/>:<WalletCards/>} title={`No hay ${isCategory?'categorías':'métodos de pago'}`} text="Crea el primer registro para comenzar."/>}
    <Modal open={open} title={`${editing?'Editar':'Nueva'} ${isCategory?'categoría':'método de pago'}`} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><label><span>Nombre</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={isCategory?'Ej. Alimentación':'Ej. Tarjeta de crédito'}/><FieldError errors={errors} name="name"/></label>{isCategory?<label><span>Color</span><div className="color-picker">{colors.map(color=><button type="button" key={color} className={form.detail===color?'selected':''} style={{background:color}} onClick={()=>setForm({...form,detail:color})}/>)}</div><FieldError errors={errors} name="color"/></label>:<label><span>Identificador visual</span><select value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})}>{icons.map(icon=><option key={icon} value={icon}>{icon}</option>)}</select><FieldError errors={errors} name="icon"/></label>}{editing&&<label className="toggle form-toggle"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span/>Registro activo</label>}<footer><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy}>{busy?'Guardando...':'Guardar cambios'}</button></footer></form></Modal>
  </div>
}
