import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react'
import { Download, Edit3, FileSpreadsheet, Filter, Plus, ReceiptText, Search, Trash2, Upload, X } from 'lucide-react'
import { api, ApiError, download } from '../lib/api'
import { money, shortDate, todayInput } from '../lib/format'
import type { Category, Expense, ImportResult, PagedResponse, PaymentMethod } from '../types'
import { EmptyState, FieldError, Modal, Spinner, useToast } from '../components/UI'

const initialForm={amount:'',date:todayInput(),categoryId:'',paymentMethodId:'',description:''}
export function ExpensesPage(){
  const toast=useToast(); const fileRef=useRef<HTMLInputElement>(null)
  const [data,setData]=useState<PagedResponse<Expense>|null>(null);const[categories,setCategories]=useState<Category[]>([]);const[methods,setMethods]=useState<PaymentMethod[]>([])
  const[loading,setLoading]=useState(true);const[page,setPage]=useState(1);const[filters,setFilters]=useState({search:'',categoryId:'',paymentMethodId:'',fromDate:'',toDate:''});const[showFilters,setShowFilters]=useState(false)
  const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Expense|null>(null);const[form,setForm]=useState(initialForm);const[errors,setErrors]=useState<Record<string,string[]>>({});const[busy,setBusy]=useState(false)
  const[importResult,setImportResult]=useState<ImportResult|null>(null);const[importing,setImporting]=useState(false)
  const load=async()=>{setLoading(true);try{const params=new URLSearchParams({page:String(page),pageSize:'10'});Object.entries(filters).forEach(([key,value])=>value&&params.set(key,value));const[next,cats,pays]=await Promise.all([api<PagedResponse<Expense>>(`/expenses?${params}`),api<Category[]>('/categories'),api<PaymentMethod[]>('/payment-methods')]);setData(next);setCategories(cats);setMethods(pays)}catch{toast.show('No se pudieron cargar los gastos.','error')}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),filters.search?300:0);return()=>clearTimeout(timer)},[page,filters])
  const start=(expense?:Expense)=>{setEditing(expense??null);setErrors({});setForm(expense?{amount:String(expense.amount),date:expense.date,categoryId:expense.categoryId,paymentMethodId:expense.paymentMethodId,description:expense.description??''}:initialForm);setOpen(true)}
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErrors({});try{const body={...form,amount:Number(form.amount)};if(editing)await api(`/expenses/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/expenses',{method:'POST',body:JSON.stringify(body)});toast.show(`Gasto ${editing?'actualizado':'registrado'}.`);setOpen(false);await load()}catch(error){if(error instanceof ApiError)setErrors(error.fields);toast.show(error instanceof Error?error.message:'No se pudo guardar.','error')}finally{setBusy(false)}}
  const remove=async(expense:Expense)=>{if(!confirm(`¿Eliminar el gasto de ${money(expense.amount)}?`))return;try{await api(`/expenses/${expense.id}`,{method:'DELETE'});toast.show('Gasto eliminado.');await load()}catch(error){toast.show(error instanceof Error?error.message:'No se pudo eliminar.','error')}}
  const importFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setImporting(true);setImportResult(null);try{const body=new FormData();body.append('file',file);const result=await api<ImportResult>('/expenses/import',{method:'POST',body});setImportResult(result);toast.show(`${result.importedRows} gastos importados.`);await load()}catch(error){toast.show(error instanceof Error?error.message:'No se pudo importar.','error')}finally{setImporting(false);e.target.value=''}}
  const clearFilters=()=>{setFilters({search:'',categoryId:'',paymentMethodId:'',fromDate:'',toDate:''});setPage(1)}
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">MOVIMIENTOS</span><h1>Gastos</h1><p>Consulta, filtra e importa todos tus movimientos.</p></div><div className="heading-actions"><button className="btn ghost" onClick={()=>fileRef.current?.click()} disabled={importing}><Upload size={18}/>{importing?'Importando...':'Importar Excel'}</button><input ref={fileRef} type="file" hidden accept=".xlsx" onChange={importFile}/><button className="btn primary" onClick={()=>start()}><Plus size={18}/>Nuevo gasto</button></div></div>
    {importResult&&<div className={`import-result ${importResult.failedRows?'warning':'success'}`}><FileSpreadsheet/><div><strong>Importación completada: {importResult.importedRows} correctos, {importResult.failedRows} con errores</strong>{importResult.errors.slice(0,4).map(error=><small key={error.rowNumber}>Fila {error.rowNumber}: {error.message}</small>)}</div><button className="icon-btn" onClick={()=>setImportResult(null)}><X/></button></div>}
    <section className="card expense-toolbar"><div className="search-box"><Search/><input placeholder="Buscar en descripciones..." value={filters.search} onChange={e=>{setPage(1);setFilters({...filters,search:e.target.value})}}/></div><button className={`btn ghost ${showFilters?'active':''}`} onClick={()=>setShowFilters(!showFilters)}><Filter size={18}/>Filtros</button><button className="btn text" onClick={()=>download('/expenses/import/template')}><Download size={17}/>Plantilla</button></section>
    {showFilters&&<section className="card filters-panel"><label><span>Desde</span><input type="date" value={filters.fromDate} onChange={e=>{setPage(1);setFilters({...filters,fromDate:e.target.value})}}/></label><label><span>Hasta</span><input type="date" value={filters.toDate} onChange={e=>{setPage(1);setFilters({...filters,toDate:e.target.value})}}/></label><label><span>Categoría</span><select value={filters.categoryId} onChange={e=>{setPage(1);setFilters({...filters,categoryId:e.target.value})}}><option value="">Todas</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Método</span><select value={filters.paymentMethodId} onChange={e=>{setPage(1);setFilters({...filters,paymentMethodId:e.target.value})}}><option value="">Todos</option>{methods.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="btn text" onClick={clearFilters}>Limpiar</button></section>}
    {loading?<Spinner/>:data?.items.length?<section className="card table-card"><div className="table-scroll"><table><thead><tr><th>Gasto</th><th>Categoría</th><th>Método</th><th>Fecha</th><th className="amount-cell">Monto</th><th/></tr></thead><tbody>{data.items.map(expense=><tr key={expense.id}><td><div className="expense-name"><span style={{background:`${expense.categoryColor}18`,color:expense.categoryColor}}><ReceiptText size={18}/></span><div><strong>{expense.description||'Sin descripción'}</strong><small>#{expense.id.slice(0,8)}</small></div></div></td><td><span className="badge"><i style={{background:expense.categoryColor}}/>{expense.categoryName}</span></td><td>{expense.paymentMethodName}</td><td>{shortDate(expense.date)}</td><td className="amount-cell"><strong>{money(expense.amount)}</strong></td><td><div className="row-actions"><button className="icon-btn" onClick={()=>start(expense)}><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>remove(expense)}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div><footer className="pagination"><span>Mostrando {data.items.length} de {data.totalCount}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page} de {Math.max(data.totalPages,1)}</span><button disabled={page>=data.totalPages} onClick={()=>setPage(page+1)}>Siguiente</button></div></footer></section>:<EmptyState icon={<ReceiptText/>} title="No encontramos gastos" text="Registra uno nuevo o modifica los filtros."/>}
    <Modal open={open} title={editing?'Editar gasto':'Registrar gasto'} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><div className="form-grid"><label><span>Monto (RD$)</span><input autoFocus type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00"/><FieldError errors={errors} name="amount"/></label><label><span>Fecha</span><input type="date" max={todayInput()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><FieldError errors={errors} name="date"/></label><label><span>Categoría</span><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Selecciona...</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><FieldError errors={errors} name="categoryId"/></label><label><span>Método de pago</span><select value={form.paymentMethodId} onChange={e=>setForm({...form,paymentMethodId:e.target.value})}><option value="">Selecciona...</option>{methods.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><FieldError errors={errors} name="paymentMethodId"/></label></div><label><span>Descripción <small>(opcional)</small></span><textarea rows={3} maxLength={300} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="¿En qué gastaste?"/><FieldError errors={errors} name="description"/></label>{(!categories.length||!methods.length)&&<div className="form-alert">Necesitas al menos una categoría y un método de pago activos.</div>}<footer><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy||!categories.length||!methods.length}>{busy?'Guardando...':'Guardar gasto'}</button></footer></form></Modal>
  </div>
}
